package com.project.tobe.customer;

import lombok.Data;

@Data //getter, setter
public class Criteria {
    //화면에 전달할 값들을 가지고 다니는 클래스
    private int page; //현재 조회하는 페이지
    private int amount; //조회하는 데이터개수 10개로

    // 검색 키워드
    private String customerNo; // 고객 번호
    private String customerName; // 고객명
    private String customerAddr; // 고객 주소
    private String customerTel; // 고객 연락처
    private String postNum; // 우편번호
    private String businessRegistrationNo; // 사업자 등록 번호
    private String nation; // 국가
    private String dealType; // 거래 유형
    private String picName; // 담당자명
    private String picEmail; // 담당자 이메일
    private String picTel; // 담당자 연락처
    private String activated; // 활성화 여부

    //.........

    // Constructor, getters, setters, and other methods will be generated by Lombok


    public Criteria() {
       this(1, 10);
    }
    public Criteria(int page, int amount) {
       this.page = page;
       this.amount = amount;
    }
    //offset - limit함수에 앞에 전달될 값
    public int getPageStart() {
        return (page - 1) * amount;
    }





}
